- name: Application control functional verification
  hosts: all
  become: yes
  gather_facts: no
  remote_user: user1

  tasks:
    - block:
      - name: Collect a file to execute
        ansible.builtin.get_url:
          url: https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.4/cowsay_2.0.4_Linux_x86_64.tar.gz
          dest: /home/user1/cowsay.tar.gz

      - name: Unarchive the tar-ball
        ansible.builtin.unarchive:
          src: cowsay.tar.gz
          dest: /home/user1/
          remote_src: yes

      - name: Execute the binary
        ansible.builtin.command: "runuser -u user1 /home/user1/cowsay 'moooooooo'"
        register: cowsay_cmd
        failed_when: cowsay_cmd.rc == 0

      rescue:
        - name: Catch any failures
          ansible.builtin.debug:
            msg: "The verification test failed! You should definitely investigate this."  

      always:
        - name: Clean up testing files
          ansible.builtin.file:
            state: absent
            dest: "{{ item }}"
          loop:
            - /home/user1/cowsay
            - /home/user1/cowthink
            - /home/user1/cowsay.tar.gz
            - /home/user1/LICENSE
            - /home/user1/doc
